alias makeall='make -j4; make -j4 install'
alias makeall_modules='make -j4 modules; make -j4 modules_install'
alias smount='mount /dev/sdb1 /mnt/mysdb/; echo noop > /sys/block/sdb/queue/scheduler'
alias sumount='umount /mnt/mysdb/'
alias clcache='echo 3 > /proc/sys/vm/drop_caches'
alias scheck='e2fsck /dev/sdb1/'
